"""add_phase_4_tables

Revision ID: 0200e0b2168d
Revises: b9d91f269194
Create Date: 2026-06-29 16:56:59.797167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0200e0b2168d'
down_revision: Union[str, Sequence[str], None] = 'b9d91f269194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_build_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('alias_text', sa.String(length=512), nullable=False),
    sa.Column('alias_type', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citation_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('citation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('citation_id', sa.String(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('citations', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('citations', sa.Column('government_update_id', sa.String(length=36), nullable=True))
    op.add_column('citations', sa.Column('client_id', sa.String(length=36), nullable=True))
    op.add_column('citations', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('paragraph_number', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('line_start', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('line_end', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('section_reference', sa.String(length=255), nullable=True))
    op.add_column('citations', sa.Column('act_reference', sa.String(length=255), nullable=True))
    op.add_column('citations', sa.Column('rule_reference', sa.String(length=255), nullable=True))
    op.add_column('citations', sa.Column('circular_number', sa.String(length=255), nullable=True))
    op.add_column('citations', sa.Column('notification_number', sa.String(length=255), nullable=True))
    op.add_column('citations', sa.Column('judgment_reference', sa.String(length=255), nullable=True))
    op.add_column('citations', sa.Column('quote_text', sa.Text(), nullable=True))
    op.add_column('citations', sa.Column('normalized_text', sa.Text(), nullable=True))
    op.add_column('citations', sa.Column('source_url', sa.String(length=512), nullable=True))
    op.add_column('citations', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.alter_column('citations', 'source_document_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('citations', 'target_entity_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'target_entity_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('citations', 'source_document_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('citations', 'confidence_score')
    op.drop_column('citations', 'source_url')
    op.drop_column('citations', 'normalized_text')
    op.drop_column('citations', 'quote_text')
    op.drop_column('citations', 'judgment_reference')
    op.drop_column('citations', 'notification_number')
    op.drop_column('citations', 'circular_number')
    op.drop_column('citations', 'rule_reference')
    op.drop_column('citations', 'act_reference')
    op.drop_column('citations', 'section_reference')
    op.drop_column('citations', 'line_end')
    op.drop_column('citations', 'line_start')
    op.drop_column('citations', 'paragraph_number')
    op.drop_column('citations', 'page_number')
    op.drop_column('citations', 'client_id')
    op.drop_column('citations', 'government_update_id')
    op.drop_column('citations', 'source_type')
    op.drop_table('source_claims')
    op.drop_table('citation_verifications')
    op.drop_table('entity_aliases')
    op.drop_table('legal_references')
    op.drop_table('graph_build_jobs')
    # ### end Alembic commands ###
