"""Add Phase 3 tables and columns

Revision ID: b9d91f269194
Revises: 9f2b5a1bf741
Create Date: 2026-06-29 14:46:48.988782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d91f269194'
down_revision: Union[str, Sequence[str], None] = '9f2b5a1bf741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_sync_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('sync_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('documents_downloaded', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['government_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('government_update_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('government_update_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('raw_file_path', sa.String(length=512), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('added_paragraphs', sa.JSON(), nullable=True),
    sa.Column('removed_paragraphs', sa.JSON(), nullable=True),
    sa.Column('changed_sections', sa.JSON(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('structured_differences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['government_update_id'], ['government_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('government_sources', sa.Column('health', sa.String(length=50), nullable=False))
    op.add_column('government_sources', sa.Column('sync_frequency', sa.String(length=100), nullable=False))
    op.add_column('government_sources', sa.Column('last_success', sa.DateTime(), nullable=True))
    op.add_column('government_sources', sa.Column('last_failure', sa.DateTime(), nullable=True))
    op.add_column('government_sources', sa.Column('average_response_time', sa.Float(), nullable=False))
    op.add_column('government_sources', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('government_sources', sa.Column('total_documents_count', sa.Integer(), nullable=False))
    op.add_column('government_sources', sa.Column('version_count', sa.Integer(), nullable=False))
    op.add_column('government_sources', sa.Column('rate_limits', sa.String(length=100), nullable=False))
    op.add_column('government_sources', sa.Column('connector_status', sa.String(length=50), nullable=False))
    op.add_column('government_sources', sa.Column('auth_requirements', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('government_sources', 'auth_requirements')
    op.drop_column('government_sources', 'connector_status')
    op.drop_column('government_sources', 'rate_limits')
    op.drop_column('government_sources', 'version_count')
    op.drop_column('government_sources', 'total_documents_count')
    op.drop_column('government_sources', 'retry_count')
    op.drop_column('government_sources', 'average_response_time')
    op.drop_column('government_sources', 'last_failure')
    op.drop_column('government_sources', 'last_success')
    op.drop_column('government_sources', 'sync_frequency')
    op.drop_column('government_sources', 'health')
    op.drop_table('government_update_versions')
    op.drop_table('connector_sync_logs')
    # ### end Alembic commands ###
