"""add_notifications_table

Revision ID: bf5c2a9d4df0
Revises: c391fbe003b3
Create Date: 2026-07-02 19:01:42.801136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5c2a9d4df0'
down_revision: Union[str, Sequence[str], None] = 'c391fbe003b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_suggestion_id', sa.String(length=36), nullable=True),
    sa.Column('related_government_update_id', sa.String(length=36), nullable=True),
    sa.Column('related_compliance_task_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_compliance_task_id'], ['compliance_tasks.id'], ),
    sa.ForeignKeyConstraint(['related_government_update_id'], ['government_updates.id'], ),
    sa.ForeignKeyConstraint(['related_suggestion_id'], ['suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_client_id'), 'notifications', ['client_id'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected drift on ais_entries/form26as_entries (stale
    # columns from an older schema, missing FK) present in the local dev sqlite file.
    # That drift is pre-existing, unrelated to this feature, and not verified against
    # production — intentionally not included here (see prior migrations for the same note).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_client_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
