"""add_intelligence_engine_suggestions_tables

Revision ID: c391fbe003b3
Revises: f5936021fcf8
Create Date: 2026-07-02 18:27:06.128202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c391fbe003b3'
down_revision: Union[str, Sequence[str], None] = 'f5936021fcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('related_document_ids', sa.JSON(), nullable=True),
    sa.Column('related_government_update_id', sa.String(length=36), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('in_progress_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_by', sa.String(length=36), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_government_update_id'], ['government_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_client_id'), 'suggestions', ['client_id'], unique=False)
    op.create_index(op.f('ix_suggestions_dedup_key'), 'suggestions', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_suggestions_organization_id'), 'suggestions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_suggestions_rule_key'), 'suggestions', ['rule_key'], unique=False)
    op.create_table('suggestion_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('suggestion_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_evidence_suggestion_id'), 'suggestion_evidence', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected drift on ais_entries/form26as_entries (stale
    # columns from an older schema, missing FK) present in the local dev sqlite file.
    # That drift is pre-existing, unrelated to this feature, and not verified against
    # production — intentionally not included here.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_evidence_suggestion_id'), table_name='suggestion_evidence')
    op.drop_table('suggestion_evidence')
    op.drop_index(op.f('ix_suggestions_rule_key'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_organization_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_dedup_key'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_client_id'), table_name='suggestions')
    op.drop_table('suggestions')
    # ### end Alembic commands ###
