"""add_phase_5_document_intelligence_tables

Revision ID: de0a4f2b8bff
Revises: f7ccf69a9083
Create Date: 2026-06-29 23:33:40.789264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0a4f2b8bff'
down_revision: Union[str, Sequence[str], None] = 'f7ccf69a9083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ais_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('assessment_year', sa.String(length=10), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=True),
    sa.Column('bank_interest', sa.Float(), nullable=True),
    sa.Column('dividend', sa.Float(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('purchase_transactions', sa.Float(), nullable=True),
    sa.Column('sale_transactions', sa.Float(), nullable=True),
    sa.Column('foreign_remittance', sa.Float(), nullable=True),
    sa.Column('sft', sa.Text(), nullable=True),
    sa.Column('property', sa.Float(), nullable=True),
    sa.Column('securities', sa.Float(), nullable=True),
    sa.Column('crypto', sa.Float(), nullable=True),
    sa.Column('high_value_transactions', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ais_entries_document_id'), 'ais_entries', ['document_id'], unique=False)
    op.create_table('balance_sheet_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=True),
    sa.Column('assets', sa.Float(), nullable=True),
    sa.Column('liabilities', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('non_current_assets', sa.Float(), nullable=True),
    sa.Column('fixed_assets', sa.Float(), nullable=True),
    sa.Column('loans', sa.Float(), nullable=True),
    sa.Column('reserves', sa.Float(), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_sheet_items_document_id'), 'balance_sheet_items', ['document_id'], unique=False)
    op.create_table('bank_statement_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('account_holder', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('particulars', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('upi_ref', sa.String(length=100), nullable=True),
    sa.Column('neft_rtgs_ref', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('running_balance', sa.Float(), nullable=True),
    sa.Column('monthly_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statement_transactions_document_id'), 'bank_statement_transactions', ['document_id'], unique=False)
    op.create_table('challan_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=True),
    sa.Column('bsr_code', sa.String(length=20), nullable=True),
    sa.Column('date_of_deposit', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('tax_period', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_entries_document_id'), 'challan_entries', ['document_id'], unique=False)
    op.create_table('deductor_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('deductor_name', sa.String(length=255), nullable=True),
    sa.Column('deductor_tan', sa.String(length=10), nullable=True),
    sa.Column('total_tds', sa.Float(), nullable=True),
    sa.Column('total_tcs', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deductor_entries_document_id'), 'deductor_entries', ['document_id'], unique=False)
    op.create_table('document_ai_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('key_insights', sa.JSON(), nullable=True),
    sa.Column('compliance_issues', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_ai_summaries_document_id'), 'document_ai_summaries', ['document_id'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('working_capital', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_ratios_document_id'), 'financial_ratios', ['document_id'], unique=False)
    op.create_table('form26as_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('assessment_year', sa.String(length=10), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=True),
    sa.Column('taxpayer_name', sa.String(length=255), nullable=True),
    sa.Column('deductor_name', sa.String(length=255), nullable=True),
    sa.Column('deductor_tan', sa.String(length=10), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('amount_credited', sa.Float(), nullable=True),
    sa.Column('tax_deducted', sa.Float(), nullable=True),
    sa.Column('tax_deposited', sa.Float(), nullable=True),
    sa.Column('refund', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('demand', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form26as_entries_document_id'), 'form26as_entries', ['document_id'], unique=False)
    op.create_table('gst_notice_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('notice_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('reply_due_date', sa.DateTime(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('tax_period', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('referenced_sections', sa.Text(), nullable=True),
    sa.Column('referenced_notifications', sa.Text(), nullable=True),
    sa.Column('referenced_circulars', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_notice_entries_document_id'), 'gst_notice_entries', ['document_id'], unique=False)
    op.create_table('tax_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('total_taxable_income', sa.Float(), nullable=True),
    sa.Column('total_tax_paid', sa.Float(), nullable=True),
    sa.Column('refund_claimed', sa.Float(), nullable=True),
    sa.Column('interest_payable', sa.Float(), nullable=True),
    sa.Column('outstanding_demand', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_summaries_document_id'), 'tax_summaries', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('ocr_provider', sa.String(length=50), nullable=True))
    op.add_column('raw_documents', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('raw_documents', sa.Column('ocr_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_documents', 'ocr_provider')
    op.drop_column('raw_documents', 'classification')
    op.drop_column('documents', 'ocr_provider')
    op.drop_column('documents', 'classification')
    op.drop_index(op.f('ix_tax_summaries_document_id'), table_name='tax_summaries')
    op.drop_table('tax_summaries')
    op.drop_index(op.f('ix_gst_notice_entries_document_id'), table_name='gst_notice_entries')
    op.drop_table('gst_notice_entries')
    op.drop_index(op.f('ix_form26as_entries_document_id'), table_name='form26as_entries')
    op.drop_table('form26as_entries')
    op.drop_index(op.f('ix_financial_ratios_document_id'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index(op.f('ix_document_ai_summaries_document_id'), table_name='document_ai_summaries')
    op.drop_table('document_ai_summaries')
    op.drop_index(op.f('ix_deductor_entries_document_id'), table_name='deductor_entries')
    op.drop_table('deductor_entries')
    op.drop_index(op.f('ix_challan_entries_document_id'), table_name='challan_entries')
    op.drop_table('challan_entries')
    op.drop_index(op.f('ix_bank_statement_transactions_document_id'), table_name='bank_statement_transactions')
    op.drop_table('bank_statement_transactions')
    op.drop_index(op.f('ix_balance_sheet_items_document_id'), table_name='balance_sheet_items')
    op.drop_table('balance_sheet_items')
    op.drop_index(op.f('ix_ais_entries_document_id'), table_name='ais_entries')
    op.drop_table('ais_entries')
    # ### end Alembic commands ###
