"""add_performance_indexes

Revision ID: f7ccf69a9083
Revises: 0200e0b2168d
Create Date: 2026-06-29 17:19:10.492323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ccf69a9083'
down_revision: Union[str, Sequence[str], None] = '0200e0b2168d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_citations_client_id'), 'citations', ['client_id'], unique=False)
    op.create_index(op.f('ix_citations_government_update_id'), 'citations', ['government_update_id'], unique=False)
    op.create_index(op.f('ix_citations_organization_id'), 'citations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_citations_source_document_id'), 'citations', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_citations_source_type'), 'citations', ['source_type'], unique=False)
    op.create_index(op.f('ix_citations_target_entity_id'), 'citations', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_clients_GSTIN'), 'clients', ['GSTIN'], unique=False)
    op.create_index(op.f('ix_clients_PAN'), 'clients', ['PAN'], unique=False)
    op.create_index(op.f('ix_clients_TAN'), 'clients', ['TAN'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_versions_organization_id'), 'document_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_versions_raw_document_id'), 'document_versions', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_embeddings_knowledge_chunk_id'), 'embeddings', ['knowledge_chunk_id'], unique=False)
    op.create_index(op.f('ix_embeddings_organization_id'), 'embeddings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_organization_id'), 'entities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entities_value'), 'entities', ['value'], unique=False)
    op.create_index(op.f('ix_entity_relationships_organization_id'), 'entity_relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_government_sources_source_name'), 'government_sources', ['source_name'], unique=False)
    op.create_index(op.f('ix_government_updates_document_number'), 'government_updates', ['document_number'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_organization_id'), 'knowledge_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_processed_document_id'), 'knowledge_chunks', ['processed_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_organization_id'), 'knowledge_graph_edges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_source_node_id'), 'knowledge_graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_target_node_id'), 'knowledge_graph_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_node_type'), 'knowledge_graph_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_organization_id'), 'knowledge_graph_nodes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processed_documents_organization_id'), 'processed_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processed_documents_raw_document_id'), 'processed_documents', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_processing_errors_organization_id'), 'processing_errors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processing_errors_pipeline_id'), 'processing_errors', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_processing_pipeline_organization_id'), 'processing_pipeline', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processing_pipeline_raw_document_id'), 'processing_pipeline', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_client_id'), 'raw_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_organization_id'), 'raw_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_structured_documents_organization_id'), 'structured_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_structured_documents_raw_document_id'), 'structured_documents', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_structured_invoice_data_GSTIN'), 'structured_invoice_data', ['GSTIN'], unique=False)
    op.create_index(op.f('ix_structured_invoice_data_organization_id'), 'structured_invoice_data', ['organization_id'], unique=False)
    op.create_index(op.f('ix_structured_invoice_data_raw_document_id'), 'structured_invoice_data', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_structured_notice_data_organization_id'), 'structured_notice_data', ['organization_id'], unique=False)
    op.create_index(op.f('ix_structured_notice_data_raw_document_id'), 'structured_notice_data', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_structured_notice_data_raw_document_id'), table_name='structured_notice_data')
    op.drop_index(op.f('ix_structured_notice_data_organization_id'), table_name='structured_notice_data')
    op.drop_index(op.f('ix_structured_invoice_data_raw_document_id'), table_name='structured_invoice_data')
    op.drop_index(op.f('ix_structured_invoice_data_organization_id'), table_name='structured_invoice_data')
    op.drop_index(op.f('ix_structured_invoice_data_GSTIN'), table_name='structured_invoice_data')
    op.drop_index(op.f('ix_structured_documents_raw_document_id'), table_name='structured_documents')
    op.drop_index(op.f('ix_structured_documents_organization_id'), table_name='structured_documents')
    op.drop_index(op.f('ix_raw_documents_organization_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_client_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_processing_pipeline_raw_document_id'), table_name='processing_pipeline')
    op.drop_index(op.f('ix_processing_pipeline_organization_id'), table_name='processing_pipeline')
    op.drop_index(op.f('ix_processing_errors_pipeline_id'), table_name='processing_errors')
    op.drop_index(op.f('ix_processing_errors_organization_id'), table_name='processing_errors')
    op.drop_index(op.f('ix_processed_documents_raw_document_id'), table_name='processed_documents')
    op.drop_index(op.f('ix_processed_documents_organization_id'), table_name='processed_documents')
    op.drop_index(op.f('ix_knowledge_graph_nodes_organization_id'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_node_type'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_edges_target_node_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_source_node_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_organization_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_chunks_processed_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_organization_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_government_updates_document_number'), table_name='government_updates')
    op.drop_index(op.f('ix_government_sources_source_name'), table_name='government_sources')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_organization_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entities_value'), table_name='entities')
    op.drop_index(op.f('ix_entities_organization_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_embeddings_organization_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_knowledge_chunk_id'), table_name='embeddings')
    op.drop_index(op.f('ix_document_versions_raw_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_organization_id'), table_name='document_versions')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_TAN'), table_name='clients')
    op.drop_index(op.f('ix_clients_PAN'), table_name='clients')
    op.drop_index(op.f('ix_clients_GSTIN'), table_name='clients')
    op.drop_index(op.f('ix_citations_target_entity_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_source_type'), table_name='citations')
    op.drop_index(op.f('ix_citations_source_document_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_organization_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_government_update_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_client_id'), table_name='citations')
    # ### end Alembic commands ###
